#!/bin/bash

# ═══════════════════════════════════════════════════════════════════════════
#  OPTISCALER UNIVERSAL - CONFIGURATION GENERATOR
# ═══════════════════════════════════════════════════════════════════════════
#
#  Generates optimized OptiScaler and fakenvapi configurations based on:
#  - GPU detection results
#  - User upscaler selection (or auto-detection)
#  - GPU-specific tuning profiles
#
# ═══════════════════════════════════════════════════════════════════════════

# Generate OptiScaler.ini based on GPU profile and user selection
generate_optiscaler_ini() {
    local gpu_profile="$1"
    local output_file="$2"
    
    log_info "Generating OptiScaler.ini from profile: $gpu_profile"
    
    # ───────────────────────────────────────────────────────────────────────
    # Check if selector provided configuration
    # ───────────────────────────────────────────────────────────────────────
    local dx12_upscaler="${SELECTED_UPSCALER}"
    local upscaler_input="${SELECTED_UPSCALER_INPUT}"
    local frame_gen="${ENABLE_FRAME_GEN:-false}"
    
    # If selector didn't run, use auto-detection based on GPU
    if [ -z "$dx12_upscaler" ]; then
        case "$GPU_GENERATION" in
            "RDNA4")
                dx12_upscaler="fsr4"
                upscaler_input="fsr31"
                frame_gen="true"
                ;;
            "RDNA3"|"RDNA2")
                dx12_upscaler="fsr31_12"
                upscaler_input="dlss"  # DLSS inputs for best quality
                frame_gen="true"
                ;;
            "RDNA1")
                dx12_upscaler="fsr31_12"
                upscaler_input="fsr31"
                frame_gen="false"
                ;;
            "Arc")
                dx12_upscaler="xess"
                upscaler_input="xess"
                frame_gen="false"
                ;;
            "RTX"*)
                dx12_upscaler="dlss"
                upscaler_input="dlss"
                frame_gen="false"
                ;;
            *)
                dx12_upscaler="fsr31_12"
                upscaler_input="fsr31"
                frame_gen="false"
                ;;
        esac
    fi
    
    # ───────────────────────────────────────────────────────────────────────
    # GPU-specific tuning parameters
    # ───────────────────────────────────────────────────────────────────────
    local dx11_upscaler="fsr31_12"
    local enable_dlss_inputs="true"
    local fsr4_update="false"
    local sharpness="0.4"
    local override_nvapi="false"
    local high_res_mv="auto"
    local enable_cas="true"
    
    # Adjust based on GPU generation
    case "$GPU_GENERATION" in
        "RDNA4")
            fsr4_update="true"
            sharpness="0.35"
            override_nvapi="true"
            high_res_mv="true"
            dx11_upscaler="fsr4"
            ;;
        "RDNA3")
            fsr4_update="false"
            sharpness="0.3"
            override_nvapi="true"
            high_res_mv="auto"
            ;;
        "RDNA2")
            fsr4_update="false"
            sharpness="0.4"
            override_nvapi="true"
            high_res_mv="false"
            ;;
        "RDNA1")
            sharpness="0.45"
            override_nvapi="true"
            high_res_mv="false"
            ;;
        "Arc")
            dx11_upscaler="xess_12"
            sharpness="0.35"
            override_nvapi="false"
            high_res_mv="auto"
            ;;
        "RTX"*)
            dx11_upscaler="dlss"
            enable_dlss_inputs="false"
            sharpness="0.3"
            override_nvapi="false"
            enable_cas="false"
            ;;
    esac
    
    # ───────────────────────────────────────────────────────────────────────
    # Log configuration being applied
    # ───────────────────────────────────────────────────────────────────────
    log_info "Configuration Summary:"
    log_info "  DX12 Upscaler: ${dx12_upscaler^^}"
    log_info "  DX11 Upscaler: ${dx11_upscaler^^}"
    log_info "  Upscaler Input: ${upscaler_input^^}"
    log_info "  Frame Generation: ${frame_gen}"
    log_info "  Sharpness: ${sharpness}"
    log_info "  High Res MV: ${high_res_mv}"
    
    # ───────────────────────────────────────────────────────────────────────
    # Generate OptiScaler.ini configuration file
    # ───────────────────────────────────────────────────────────────────────
    cat > "$output_file" << EOF
; ═══════════════════════════════════════════════════════════════════════════
;  OptiScaler Configuration
;  Generated by OptiScaler Universal v0.1.0-alpha
; ═══════════════════════════════════════════════════════════════════════════
;
;  GPU Information:
;    Vendor: $GPU_VENDOR
;    Generation: $GPU_GENERATION
;    Model: $GPU_MODEL
;    Profile: $gpu_profile
;
;  Configuration:
;    Upscaler: ${dx12_upscaler^^}
;    Input Method: ${upscaler_input^^}
;    Frame Generation: ${frame_gen}
;
;  Generated: $(date '+%Y-%m-%d %H:%M:%S')
;
; ═══════════════════════════════════════════════════════════════════════════

[General]
Enabled=true

[Upscalers]
Dx12Upscaler=${dx12_upscaler}
Dx11Upscaler=${dx11_upscaler}
VulkanUpscaler=auto

[Inputs]
UpscalerInput=${upscaler_input}
EnableDlssInputs=${enable_dlss_inputs}
EnableXeSSInputs=auto
EnableFsr2Inputs=auto
EnableFsr3Inputs=auto

[FrameGeneration]
FrameGen=${frame_gen}
FrameGenMod=enabled
UseOpticalFlow=true

[FSR]
Fsr4Update=${fsr4_update}
FsrNonLinearSRGB=true
FsrNonLinearPQ=false

[Quality]
HighResMV=${high_res_mv}
DynamicResolution=true

[Sharpness]
OverrideSharpness=true
Sharpness=${sharpness}

[CAS]
Enabled=${enable_cas}
MotionSharpnessEnabled=true
MotionSharpness=0.5

[Performance]
AsyncCompute=true
UsePrecompiledShaders=true

[Spoofing]
StreamlineSpoofing=true
Dxgi=auto

[NvApi]
OverrideNvapiDll=${override_nvapi}
Nvapi=true

[Overlay]
EnableOverlay=true
ShortcutKey=0x2D

[Compatibility]
DisableReactiveMask=false

[Log]
LogToFile=true
LogLevel=2
EOF
    
    log_success "OptiScaler.ini generated: $output_file"
}

# ═══════════════════════════════════════════════════════════════════════════
#  Generate fakenvapi.ini for non-NVIDIA GPUs
#  Enables Anti-Lag 2/Reflex-like features on AMD/Intel GPUs
# ═══════════════════════════════════════════════════════════════════════════

generate_fakenvapi_ini() {
    local output_file="$1"
    
    # Skip for NVIDIA GPUs (they have native Reflex support)
    if [[ "$GPU_VENDOR" == "NVIDIA" ]]; then
        log_info "Skipping fakenvapi.ini (NVIDIA has native Reflex support)"
        return 0
    fi
    
    log_info "Generating fakenvapi.ini for $GPU_VENDOR GPU"
    
    # ───────────────────────────────────────────────────────────────────────
    # Detect Anti-Lag support based on GPU generation
    # ───────────────────────────────────────────────────────────────────────
    local anti_lag_mode="0"
    local boost_mode="0"
    local anti_lag_name="None"
    
    if [[ "$GPU_VENDOR" == "AMD" ]]; then
        # Check for Anti-Lag 2 support (RDNA2+)
        if [[ " ${GPU_CAPABILITIES[@]} " =~ " ANTI_LAG_2 " ]] || \
           [[ "$GPU_GENERATION" =~ ^RDNA[234]$ ]]; then
            anti_lag_mode="2"
            boost_mode="1"
            anti_lag_name="Anti-Lag 2 (RDNA2+)"
        elif [[ "$GPU_GENERATION" == "RDNA1" ]]; then
            anti_lag_mode="1"
            boost_mode="0"
            anti_lag_name="Anti-Lag (RDNA1)"
        else
            anti_lag_mode="1"
            boost_mode="0"
            anti_lag_name="Anti-Lag (Legacy)"
        fi
        log_info "  Latency Reduction: ${anti_lag_name}"
    else
        log_info "  Latency Reduction: Software emulation"
    fi
    
    # ───────────────────────────────────────────────────────────────────────
    # GPU spoofing for DLSS inputs on AMD/Intel
    # ───────────────────────────────────────────────────────────────────────
    local spoof_gpu="false"
    local gpu_model="4095"  # RTX 4090
    local gpu_name="NVIDIA GeForce RTX 4090"
    
    if [[ " ${GPU_CAPABILITIES[@]} " =~ " DLSS_INPUTS_RECOMMENDED " ]]; then
        spoof_gpu="true"
        log_info "  GPU Spoofing: Enabled (spoofing RTX 4090 for DLSS inputs)"
    else
        log_info "  GPU Spoofing: Disabled"
    fi
    
    # ───────────────────────────────────────────────────────────────────────
    # Generate fakenvapi.ini configuration file
    # ───────────────────────────────────────────────────────────────────────
    cat > "$output_file" << EOF
; ═══════════════════════════════════════════════════════════════════════════
;  fakenvapi Configuration (dxvk-nvapi)
;  Generated by OptiScaler Universal v0.1.0-alpha
; ═══════════════════════════════════════════════════════════════════════════
;
;  Purpose: Enable NVIDIA Reflex-like features on AMD/Intel GPUs
;
;  GPU Information:
;    Real GPU: $GPU_VENDOR $GPU_GENERATION ($GPU_MODEL)
;    Spoofed GPU: ${gpu_name}
;    Anti-Lag: ${anti_lag_name}
;
;  Generated: $(date '+%Y-%m-%d %H:%M:%S')
;
; ═══════════════════════════════════════════════════════════════════════════

[General]
enable_logs=1
enable_trace_logs=0

[GPU]
SpoofGPU=${spoof_gpu}
GPUModel=${gpu_model}
GPUName=${gpu_name}

[Reflex]
force_reflex=${anti_lag_mode}
latencyflex_mode=2
force_latencyflex=0
boost_mode=${boost_mode}

[AMD]
EnableAntiLag=${anti_lag_mode}
EnableBoost=${boost_mode}
EnableChill=0

[Features]
EnableDLSS=${spoof_gpu}
EnableDLFG=false
EnableRayTracing=true
EOF
    
    log_success "fakenvapi.ini generated: $output_file"
}

# ═══════════════════════════════════════════════════════════════════════════
#  Export functions for use in other scripts
# ═══════════════════════════════════════════════════════════════════════════

export -f generate_optiscaler_ini
export -f generate_fakenvapi_ini

