#!/bin/bash

# ═══════════════════════════════════════════════════════════════════════════
#  OPTISCALER UNIVERSAL - CONFIGURATION GENERATOR
# ═══════════════════════════════════════════════════════════════════════════

# Generate OptiScaler.ini based on GPU profile
generate_optiscaler_ini() {
    local gpu_profile="$1"
    local output_file="$2"
    
    log_info "Generating OptiScaler.ini from profile: $gpu_profile"
    
    # Load GPU profile (simplified - in production would parse YAML)
    local dx12_upscaler="fsr31"
    local dx11_upscaler="fsr31_12"
    local enable_dlss_inputs="true"
    local fsr4_update="false"
    local sharpness="0.4"
    local override_nvapi="false"
    
    # Adjust based on GPU generation
    case "$GPU_GENERATION" in
        "RDNA4")
            fsr4_update="true"
            sharpness="0.35"
            override_nvapi="true"
            ;;
        "RDNA3"|"RDNA2")
            fsr4_update="false"
            override_nvapi="true"
            ;;
        "RDNA1")
            sharpness="0.45"
            override_nvapi="true"
            ;;
        "Arc")
            dx12_upscaler="xess"
            dx11_upscaler="xess_12"
            sharpness="0.35"
            ;;
        "RTX"*)
            dx12_upscaler="dlss"
            dx11_upscaler="dlss"
            enable_dlss_inputs="false"
            ;;
    esac
    
    cat > "$output_file" << EOF
; OptiScaler Configuration
; Generated by OptiScaler Universal
; GPU: $GPU_VENDOR $GPU_GENERATION

[General]
Enabled=true

[Upscalers]
Dx12Upscaler=$dx12_upscaler
Dx11Upscaler=$dx11_upscaler
VulkanUpscaler=auto

[Inputs]
EnableDlssInputs=$enable_dlss_inputs
EnableXeSSInputs=auto
EnableFsr2Inputs=auto
EnableFsr3Inputs=auto

[FSR]
Fsr4Update=$fsr4_update
FsrNonLinearSRGB=true
FsrNonLinearPQ=false

[Sharpness]
OverrideSharpness=true
Sharpness=$sharpness

[CAS]
Enabled=true
MotionSharpnessEnabled=true
MotionSharpness=0.5

[Spoofing]
StreamlineSpoofing=true
Dxgi=auto

[NvApi]
OverrideNvapiDll=$override_nvapi

[Menu]
ShortcutKey=0x24

[Log]
LogToFile=true
LogLevel=2
EOF
    
    log_success "OptiScaler.ini generated: $output_file"
}

# Generate fakenvapi.ini for non-NVIDIA GPUs
# Enables Anti-Lag/Reflex-like features on AMD/Intel GPUs
generate_fakenvapi_ini() {
    local output_file="$1"
    
    if [[ "$GPU_VENDOR" == "NVIDIA" ]]; then
        log_info "Skipping fakenvapi.ini (NVIDIA has native Reflex support)"
        return 0
    fi
    
    log_info "Generating fakenvapi.ini for $GPU_VENDOR GPU (enables Reflex-like features)"
    
    cat > "$output_file" << EOF
; fakenvapi Configuration
; Generated by OptiScaler Universal

[General]
enable_logs=1
enable_trace_logs=0

[Reflex]
force_reflex=2
latencyflex_mode=2
force_latencyflex=0
EOF
    
    log_success "fakenvapi.ini generated: $output_file"
}

export -f generate_optiscaler_ini
export -f generate_fakenvapi_ini
